// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzPfRZJHtkwndAndwJWSb9_LSdhnj_z60',
    appId: '1:1024481568161:web:b1790800eb56722fc357e0',
    messagingSenderId: '1024481568161',
    projectId: 'chorvacom',
    authDomain: 'chorvacom.firebaseapp.com',
    storageBucket: 'chorvacom.firebasestorage.app',
    measurementId: 'G-ETMZQGT8V8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbdDw_PncZPwlzwWgAhh780W2zrAo1xyg',
    appId: '1:1024481568161:android:5cc70d4ca7657ab9c357e0',
    messagingSenderId: '1024481568161',
    projectId: 'chorvacom',
    storageBucket: 'chorvacom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMZzDZ-xelUQ3AY3YDn0EKYt4Rx1hLuyY',
    appId: '1:1024481568161:ios:e081f5d20c2556f2c357e0',
    messagingSenderId: '1024481568161',
    projectId: 'chorvacom',
    storageBucket: 'chorvacom.firebasestorage.app',
    iosBundleId: 'com.example.chorvaYem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMZzDZ-xelUQ3AY3YDn0EKYt4Rx1hLuyY',
    appId: '1:1024481568161:ios:e081f5d20c2556f2c357e0',
    messagingSenderId: '1024481568161',
    projectId: 'chorvacom',
    storageBucket: 'chorvacom.firebasestorage.app',
    iosBundleId: 'com.example.chorvaYem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzPfRZJHtkwndAndwJWSb9_LSdhnj_z60',
    appId: '1:1024481568161:web:47fedda0637bec72c357e0',
    messagingSenderId: '1024481568161',
    projectId: 'chorvacom',
    authDomain: 'chorvacom.firebaseapp.com',
    storageBucket: 'chorvacom.firebasestorage.app',
    measurementId: 'G-1NG7Q03PBW',
  );
}
